"""Add destination and vehicle_number to Bill model

Revision ID: 986e81b92e8e
Revises: a1b2c3d4e5f6
Create Date: 2025-11-05 14:42:10.158070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '986e81b92e8e'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add destination and vehicle_number columns to bill table
    # These columns are already present in the database, so use if_not_exists pattern
    with op.batch_alter_table('bill', schema=None) as batch_op:
        # Check if columns exist, add only if missing
        connection = op.get_bind()
        inspector = sa.inspect(connection)
        columns = [col['name'] for col in inspector.get_columns('bill')]
        
        if 'destination' not in columns:
            batch_op.add_column(sa.Column('destination', sa.String(length=200), nullable=True))
        if 'vehicle_number' not in columns:
            batch_op.add_column(sa.Column('vehicle_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove destination and vehicle_number columns from bill table
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('vehicle_number')
        batch_op.drop_column('destination')
    # ### end Alembic commands ###
