AWSTemplateFormatVersion: '2010-09-09'
Description: 'Update ALB to proxy to Replit TraceTrack application'

Parameters:
  ALBListenerArn:
    Type: String
    Description: ARN of the existing ALB listener

Resources:
  # Update the existing listener to proxy to Replit
  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: 443
            Host: "#{host}"
            Path: "/#{path}"
            Query: "#{query}"
            StatusCode: HTTP_301
      Conditions:
        - Field: path-pattern
          Values: ['*']
      ListenerArn: !Ref ALBListenerArn
      Priority: 1

Outputs:
  RedirectStatus:
    Description: Redirect configuration status
    Value: "Configured to redirect HTTPS traffic"